### ISSUE TITLE
Add support for regional clusters

### ISSUE THREAD

**Issue by j-martin** [google-terraform-modules/terraform-google-kubernetes-engine#27]
Currently, it is only possible to create a zonal cluster with the module. It is supported by `container_node_pool` and is GA in GKE.

https://www.terraform.io/docs/providers/google/r/container_node_pool.html#usage-with-a-regional-cluster

https://cloud.google.com/kubernetes-engine/docs/concepts/regional-clusters?hl=en_US

**Comment by perriea** [comment]
Hi @j-martin, 
I want to do it from version 1.6 but the problem is that the `null` value is not yet available within Terraform (see the next release 0.12) and can not leave a blank value in the field `zone`.

Just wait now :)

**Comment by framled** [comment]
since region and zone going to be deprecated in favour of location. this should use location argument ;)

**Comment by perriea** [comment]
#31
