### ISSUE TITLE
google_container_engine_versions asking for project variable

### ISSUE THREAD

**Issue by adrianlop** [google-terraform-modules/terraform-google-kubernetes-engine#4]
hey guys,

I had to add the variable `project = "my-project"` in this tf datasource `google_container_engine_versions` (https://github.com/google-terraform-modules/terraform-google-kubernetes-engine/blob/master/main.tf#L5)
otherwise the module doesn't work out of the box.
According to the terraform docs, `project` is an optional parameter, but doesn't look like it.

tf version 0.11.7

am I doing something wrong?

**Comment by perriea** [comment]
Hi @adrianlop 
In which version of the provider are you ? 1.8.0 ?

It is possible that in version 1.10.0 some parameters have become mandatory and the doc is not up to date (it happens ...)

**Comment by adrianlop** [comment]
hey @perriea, yes I was in 1.8.0 but also tried 1.11 with no luck.
now I saw the new release you generated for 1.12 and it's working like a charm, plus you added support for easily create multiple node_pools which is great!

thanks for updating and fixing it, appreciate it.

**Comment by perriea** [comment]
Thanks @adrianlop, I appreciate your feedback :)
